title: Alex's Blog
author: Alex Bochannek
email: alex@bochannek.com
description: >-
  A blog about scripting, computing history, and whatever else comes up...
baseurl: ""
url: "https://abochannek.github.io"
github_username: abochannek
markdown: kramdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
